name: iCottageSMultiPlugin
version: 0.011-BETA
main: dev.cottage.iCottageSMultiPlugin.iCottageSMultiPlugin
api-version: 1.21
commands:
  tpa:
    description: Send a teleport request to another player
    usage: /<command> <player>
    permission: icottagesmulti.tpa.use

    tpaccept:
      description: Accept a pending teleport request
      usage: /<command>
      permission: icottagesmulti.tpa.use

    tpdeny:
      description: Deny a pending teleport request
      usage: /<command>
      permission: icottagesmulti.tpa.use
  createshop:
    description: Creates a new chest shop.
    usage: /createshop <sellItem> <buyItem> <sellAmount> <buyAmount>
    permission: icottagesmulti.createshop
    permission-message: You don't have permission to create a chest shop.
  removeshop:
    description: Removes the chest shop at the location you are looking at.
    usage: /removeshop
    permission: icottagesmulti.removeshop
    permission-message: You don't have permission to remove a chest shop.
  shops:
    description: Lists all shops in your current dimension, sorted by proximity or item.
    usage: /shops [proximity|item [itemName]]
    permission: icottagesmulti.listshops
    permission-message: You don't have permission to list chest shops.
permissions:
  icottagesmulti.createshop:
    description: Allows the user to create chest shops.
    default: true
  icottagesmulti.removeshop:
    description: Allows the user to remove chest shops.
    default: true
  icottagesmulti.listshops:
    description: Allows the user to list all shops.
    default: true
  icottages.admin.notifications:
    description: Receives admin notifications
    default: op
  icottages.tpa.use:
    description: Allows using the TPA command
    default: true
  icottages.tpa.accept:
    description: Allows accepting TPA requests
    default: true
  icottages.tpa.deny:
    description: Allows denying TPA requests
    default: true
